import React from 'react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const FAQ = () => {
  const faqs = [
    {
      question: "Quais são os tipos de exames de vista realizados na Ótica Gouveia?",
      answer: "A Ótica Gouveia oferece uma ampla gama de exames oftalmológicos para garantir a saúde ocular completa de nossos clientes. Realizamos exames de refração para determinar o grau exato de miopia, hipermetropia, astigmatismo e presbiopia, utilizando equipamentos de última geração que proporcionam medições precisas. Nossos exames incluem avaliação da acuidade visual, teste de campo visual para detectar possíveis alterações no campo de visão, exame de fundo de olho para verificar a saúde da retina e nervo óptico, e medição da pressão intraocular para prevenção do glaucoma. Também oferecemos avaliação da musculatura ocular para detectar problemas de coordenação dos olhos, teste de visão de cores para identificar daltonismo, e exames específicos para adaptação de lentes de contato. Todos os exames são realizados por optometristas qualificados e certificados, seguindo protocolos rigorosos de segurança e higiene. Os resultados são explicados detalhadamente ao cliente, com orientações personalizadas sobre cuidados oculares e recomendações de tratamento quando necessário."
    },
    {
      question: "Qual é a diferença entre as lentes monofocais, bifocais e multifocais?",
      answer: "As lentes monofocais são projetadas para corrigir apenas um tipo de problema de visão, seja para longe ou para perto, oferecendo um campo visual amplo e claro para a distância específica. São ideais para pessoas com miopia, hipermetropia ou astigmatismo que não apresentam presbiopia. As lentes bifocais possuem duas áreas distintas de correção: a parte superior para visão de longe e a parte inferior para visão de perto, com uma linha divisória visível entre as duas zonas. Embora sejam funcionais, podem causar desconforto inicial devido à transição abrupta entre as zonas de visão. As lentes multifocais, também conhecidas como progressivas, representam a tecnologia mais avançada, oferecendo múltiplas zonas de visão sem linhas divisórias visíveis. Elas proporcionam uma transição suave entre visão de longe, intermediária e de perto, simulando o funcionamento natural dos olhos jovens. Na Ótica Gouveia, trabalhamos com as melhores marcas de lentes multifocais, oferecendo opções personalizadas de acordo com o estilo de vida e necessidades específicas de cada cliente. Nossos especialistas realizam medições precisas e adaptação cuidadosa para garantir conforto máximo e visão nítida em todas as distâncias."
    },
    {
      question: "Como escolher a armação ideal para o meu rosto?",
      answer: "A escolha da armação ideal envolve diversos fatores que nossos consultores especialistas na Ótica Gouveia avaliam cuidadosamente. Primeiro, analisamos o formato do seu rosto - rostos redondos harmonizam melhor com armações angulares e retangulares que alongam visualmente, enquanto rostos quadrados ficam equilibrados com armações arredondadas ou ovais. Rostos ovais têm a vantagem de combinar com praticamente todos os formatos, permitindo maior flexibilidade na escolha. Consideramos também o tamanho das suas características faciais - pessoas com feições delicadas devem optar por armações mais leves e proporcionais, enquanto feições marcantes podem suportar armações mais robustas. A cor da armação deve complementar seu tom de pele e cor dos olhos - tons quentes como dourado e marrom ficam bem em peles com subtom amarelado, enquanto tons frios como prateado e azul harmonizam com peles de subtom rosado. O estilo de vida também influencia a escolha - profissionais que trabalham em escritório podem preferir armações clássicas e discretas, enquanto pessoas mais despojadas podem optar por modelos mais ousados e coloridos. Na Ótica Gouveia, oferecemos um atendimento personalizado onde você pode experimentar diferentes modelos enquanto nossos especialistas orientam sobre qual opção realça melhor suas características naturais."
    },
    {
      question: "Quais são os cuidados necessários com os óculos no dia a dia?",
      answer: "O cuidado adequado com os óculos é fundamental para manter a qualidade visual e prolongar a vida útil do produto. Na Ótica Gouveia, orientamos nossos clientes sobre práticas essenciais de manutenção. Para limpeza diária, utilize sempre produtos específicos para lentes - nunca papel higiênico, lenços de papel ou roupas, pois podem causar microriscos. Recomendamos borrifar spray limpa-lentes nas duas faces da lente e limpar suavemente com flanela de microfibra em movimentos circulares. Ao guardar os óculos, sempre utilize o estojo rígido fornecido, posicionando as lentes para cima para evitar riscos na superfície. Evite deixar os óculos no painel do carro ou expostos ao calor excessivo, pois altas temperaturas podem danificar tratamentos especiais das lentes e deformar armações de acetato. Para ajustes de armação, nunca tente fazer reparos caseiros - procure sempre nossa loja para ajustes profissionais gratuitos. Recomendamos revisões periódicas a cada seis meses para verificar alinhamento, aperto de parafusos e estado geral do produto. Mantenha sempre um kit de limpeza portátil e considere ter um óculos reserva para situações de emergência. Com esses cuidados simples, seus óculos manterão a qualidade óptica e estética por muito mais tempo."
    },
    {
      question: "A Ótica Gouveia trabalha com quais marcas de armações?",
      answer: "A Ótica Gouveia mantém um portfólio diversificado das melhores marcas nacionais e internacionais de armações, garantindo opções para todos os gostos, estilos e orçamentos. Trabalhamos com marcas premium internacionais como Ray-Ban, conhecida mundialmente por seus modelos icônicos e qualidade superior; Oakley, especializada em armações esportivas de alta performance; e Carrera, famosa por seus designs italiano elegantes e inovadores. No segmento nacional, oferecemos armações Chilli Beans, que combina modernidade e acessibilidade, e HB, marca brasileira que se destaca no segmento jovem e descolado. Para o público infantil, dispomos de linhas especializadas da Miraflex e Nano Vista, desenvolvidas especificamente para crianças com materiais flexíveis, seguros e resistentes. Também trabalhamos com marcas como Guess, Emporio Armani, Police e Diesel para clientes que buscam sofisticação e status. No segmento de armações de grau, mantemos estoques da Silhouette, conhecida por suas armações sem aro ultraleves, e da Lindberg, famosa pela qualidade dinamarquesa e design minimalista. Todas as armações passam por rigoroso controle de qualidade e vêm acompanhadas de garantia do fabricante. Nossa equipe está sempre atualizada sobre lançamentos e tendências do mercado óptico internacional."
    },
    {
      question: "Qual é o prazo de entrega dos óculos após o pedido?",
      answer: "Na Ótica Gouveia, priorizamos a agilidade na entrega sem comprometer a qualidade do produto final. Para óculos com lentes de grau simples (monofocais), o prazo padrão é de 3 a 5 dias úteis, considerando que as lentes são confeccionadas em nosso laboratório próprio com equipamentos de última geração. Lentes com tratamentos especiais como antirreflexo premium, fotossensível (transitions) ou filtro de luz azul podem levar de 5 a 7 dias úteis devido ao processo adicional de aplicação desses tratamentos. Para lentes multifocais (progressivas), que requerem cálculos mais complexos e personalização específica para cada usuário, o prazo é de 7 a 10 dias úteis. Lentes especiais como policarbonato de alto índice, cristal ou com correções muito elevadas podem necessitar de 10 a 15 dias úteis, pois muitas vezes são importadas ou requerem processos de fabricação específicos. Em casos urgentes, oferecemos serviço expresso com sobretaxa, reduzindo o prazo pela metade quando tecnicamente possível. Durante todo o processo, mantemos o cliente informado via WhatsApp sobre o andamento da produção. Ao retirar o produto, realizamos ajustes finais na armação e orientações de uso, garantindo conforto perfeito. Todos os prazos são calculados a partir da confirmação do pedido e aprovação da receita médica, excluindo finais de semana e feriados."
    },
    {
      question: "Como funciona a garantia dos produtos da Ótica Gouveia?",
      answer: "A Ótica Gouveia oferece um sistema de garantia abrangente que demonstra nossa confiança na qualidade dos produtos comercializados. Para armações, oferecemos garantia de 12 meses contra defeitos de fabricação, incluindo quebras espontâneas, descamação de tinta, defeitos em dobradiças e soldas. Esta garantia não cobre danos causados por mau uso, quedas ou acidentes. As lentes oftálmicas possuem garantia de 6 meses contra defeitos ópticos como bolhas, riscos de fabricação ou descentralização, além de garantia de 12 meses nos tratamentos antirreflexo contra descamação prematura. Lentes fotossensíveis têm garantia específica de 24 meses para o mecanismo de escurecimento e clareamento. Oferecemos também garantia de adaptação de 30 dias para lentes multifocais - se houver dificuldade de adaptação mesmo após acompanhamento profissional, realizamos troca por outro tipo de lente adequado. Nosso pós-venda inclui ajustes gratuitos da armação durante todo o período de garantia, limpeza e manutenção sem custo, e reposição imediata em caso de defeito comprovado. Para acionar a garantia, basta apresentar a nota fiscal e trazer o produto para avaliação técnica. Mantemos histórico completo de todos os clientes em nosso sistema, facilitando o atendimento. Além da garantia legal, oferecemos seguro opcional contra quebra acidental com condições especiais para nossos clientes."
    },
    {
      question: "A ótica oferece parcelamento e quais são as formas de pagamento aceitas?",
      answer: "A Ótica Gouveia disponibiliza diversas modalidades de pagamento para facilitar a aquisição de seus produtos de qualidade. Aceitamos todas as principais bandeiras de cartão de crédito (Visa, Mastercard, American Express, Elo, Hipercard) com parcelamento em até 12 vezes sem juros para compras acima de R$ 200,00. Para valores menores, oferecemos parcelamento em até 6 vezes sem juros. No cartão de débito, trabalhamos com as mesmas bandeiras mencionadas para pagamento à vista. Para maior comodidade, aceitamos PIX com desconto especial de 5% sobre o valor total da compra, e transferências bancárias dos principais bancos do país. Pagamentos em dinheiro também recebem desconto de 5% sobre o valor final. Para clientes que preferem, oferecemos crediário próprio da loja com condições especiais - entrada de 30% e saldo parcelado em até 8 vezes com juros competitivos, mediante análise de crédito simplificada. Trabalhamos também com cartões de benefícios como Sodexo, Ticket, VR e Alelo para desconto em compras dentro dos limites estabelecidos pelas operadoras. Para empresas, oferecemos condições diferenciadas com prazo estendido para pagamento e desconto progressivo conforme volume de compra. Todos os preços são transparentes, sem taxa de conveniência ou custos adicionais ocultos."
    },
    {
      question: "Vocês fazem atendimento domiciliar para idosos ou pessoas com mobilidade reduzida?",
      answer: "Sim, a Ótica Gouveia mantém um programa especial de atendimento domiciliar voltado para idosos, pessoas com mobilidade reduzida e pacientes em recuperação que não podem se deslocar até nossa loja física. Este serviço diferenciado demonstra nosso compromisso com a inclusão e acessibilidade. Nossa equipe especializada, composta por optometrista e consultor em vendas, se desloca até a residência ou local indicado pelo cliente, levando equipamentos portáteis de última geração para realizar exames completos de refração e acuidade visual. O atendimento domiciliar inclui teste de lentes, demonstração de armações adequadas ao perfil do cliente, medição precisa para confecção das lentes e orientações sobre cuidados oculares. Levamos um mostruário diversificado de armações para que o cliente possa escolher o modelo ideal no conforto de seu lar. O agendamento deve ser feito com antecedência mínima de 24 horas, e cobrimos toda a região metropolitana de Curitiba. Para este serviço, cobramos uma taxa simbólica de deslocamento que é totalmente revertida em desconto na compra dos óculos. O prazo de entrega dos produtos continua o mesmo, e realizamos a entrega final também em domicílio, fazendo os ajustes necessários na armação e garantindo o conforto perfeito. Este serviço está disponível de segunda a sábado, das 8h às 17h, mediante agendamento prévio."
    },
    {
      question: "Quais são os tipos de lentes de contato disponíveis e como fazer a adaptação?",
      answer: "A Ótica Gouveia oferece uma linha completa de lentes de contato para diversos tipos de correção visual e estilos de vida. Trabalhamos com lentes gelatinosas (hidrogel e silicone hidrogel) nas modalidades diária, quinzenal, mensal e anual, cada uma com características específicas de conforto e praticidade. Para correção de miopia e hipermetropia, dispomos de lentes esféricas das principais marcas como Acuvue, Bausch+Lomb, Cooper Vision e Alcon. Para astigmatismo, oferecemos lentes tóricas especializadas que corrigem simultaneamente miopia ou hipermetropia junto com astigmatismo. Pacientes com presbiopia podem optar por nossas lentes multifocais que proporcionam visão nítida para longe e perto simultaneamente. Também mantemos em estoque lentes coloridas para mudança ou realce da cor natural dos olhos, disponíveis com ou sem grau. O processo de adaptação inicia com exame oftalmológico completo para avaliar a saúde ocular e determinar se há contraindicações ao uso de lentes de contato. Realizamos medição da curvatura corneana, avaliação do filme lacrimal e seleção do tipo ideal de lente. O período de adaptação varia de pessoa para pessoa, iniciando com poucas horas de uso diário e aumentando gradualmente. Fornecemos kit completo com estojo, soro fisiológico e orientações detalhadas de higiene e manuseio. Oferecemos acompanhamento gratuito durante os primeiros 30 dias de adaptação."
    },
    {
      question: "A Ótica Gouveia realiza consertos e reparos em óculos de outras óticas?",
      answer: "Absolutamente! A Ótica Gouveia possui um departamento técnico especializado em consertos e reparos de óculos, independentemente do local de compra original. Nossa oficina está equipada com ferramentas profissionais e peças de reposição para os mais diversos tipos de armações e problemas. Realizamos soldas em armações metálicas usando equipamentos de solda a laser que garantem resistência e acabamento invisível. Para armações de acetato, utilizamos técnicas de colagem com adesivos especiais de grau médico que suportam o uso diário. Oferecemos troca de parafusos, plaquetas nasais, hastes e dobradiças, mantendo estoque de peças para as principais marcas do mercado. Nossos serviços incluem ajustes de armação para melhorar o conforto, substituição de lentes danificadas por novos pares idênticos, e limpeza profunda com ultrassom para remoção de oleosidade e sujeira acumulada. Para orçamentos, realizamos avaliação gratuita e informamos prazo e valor antes de iniciar qualquer reparo. A maioria dos consertos simples fica pronta no mesmo dia, enquanto reparos mais complexos podem levar de 3 a 5 dias úteis. Todos os consertos recebem garantia de 90 dias contra defeitos no serviço executado. Nosso objetivo é sempre buscar a solução mais econômica para o cliente, orientando quando vale a pena consertar ou quando é mais vantajoso adquirir um produto novo."
    },
    {
      question: "Quais são os benefícios das lentes com filtro de luz azul?",
      answer: "As lentes com filtro de luz azul, também conhecidas como lentes para uso digital, representam uma inovação importante para pessoas que passam longas horas expostas a dispositivos eletrônicos. A Ótica Gouveia oferece esta tecnologia avançada que filtra seletivamente a luz azul-violeta emitida por smartphones, tablets, computadores, televisores e lâmpadas LED. A exposição excessiva à luz azul pode causar fadiga ocular digital, caracterizada por olhos secos, vermelhidão, sensação de ardor, visão turva temporária e dores de cabeça. Nossos filtros bloqueiam aproximadamente 40% da luz azul nociva na faixa de 415-455 nanômetros, mantendo a passagem da luz azul benéfica necessária para regulação do ciclo circadiano. Os benefícios incluem redução significativa do cansaço visual, melhora na qualidade do sono quando usado próximo ao horário de dormir, maior conforto durante uso prolongado de dispositivos digitais, e proteção preventiva contra possíveis danos retinianos a longo prazo. As lentes podem ser aplicadas em qualquer tipo de correção visual - monofocais, bifocais ou multifocais - e estão disponíveis em diferentes níveis de filtragem conforme a necessidade individual. O tratamento é praticamente imperceptível, mantendo a transparência natural da lente com apenas um leve reflexo azulado na superfície. Na Ótica Gouveia, orientamos sobre o uso adequado e oferecemos período de teste para comprovar os benefícios desta tecnologia inovadora."
    },
    {
      question: "Como funciona o programa de fidelidade da Ótica Gouveia?",
      answer: "O Programa Visão Fiel da Ótica Gouveia foi desenvolvido para reconhecer e recompensar a lealdade de nossos clientes com benefícios exclusivos e vantagens progressivas. Ao realizar seu primeiro cadastro, o cliente automaticamente se torna membro do programa sem custo algum e começa a acumular pontos a cada compra realizada. O sistema de pontuação funciona da seguinte forma: cada R$ 1,00 gasto equivale a 1 ponto, e a cada 100 pontos acumulados, o cliente recebe R$ 10,00 de desconto para utilizar na próxima compra. Além da pontuação básica, oferecemos bonificações especiais - compras acima de R$ 500,00 recebem pontuação dobrada, e aniversariantes ganham 50 pontos extras no mês do aniversário. Os membros têm acesso a promoções exclusivas com descontos diferenciados, pré-venda de lançamentos, e convites para eventos especiais da ótica. Nosso programa possui três categorias: Bronze (0-499 pontos), Prata (500-999 pontos) e Ouro (acima de 1000 pontos), cada uma com benefícios crescentes como desconto progressivo, serviços prioritários e brindes exclusivos. Os pontos não têm prazo de validade enquanto o cliente mantiver atividade de compra pelo menos uma vez ao ano. Clientes categoria Ouro recebem revisão gratuita semestral dos óculos, limpeza ultrassônica profissional e atendimento preferencial. Toda movimentação de pontos pode ser acompanhada pelo aplicativo móvel ou através do nosso site."
    },
    {
      question: "A ótica oferece óculos de sol com grau? Quais são as opções disponíveis?",
      answer: "Sim, a Ótica Gouveia é especialista em óculos de sol com grau, oferecendo a combinação perfeita entre proteção solar e correção visual. Trabalhamos com as principais marcas do mercado como Ray-Ban, Oakley, Carrera, HB e Chilli Beans, todas disponíveis para receberem lentes graduadas personalizadas. Nosso laboratório próprio confecciona lentes de sol em diversos materiais e índices de refração, garantindo qualidade óptica superior e proteção UV 100%. Para lentes de sol com grau, utilizamos materiais como CR-39, policarbonato e trivex, cada um com características específicas de resistência e leveza. Oferecemos várias opções de coloração: marrom (realça contrastes e reduz reflexos), cinza (mantém cores naturais), verde (conforto visual e redução de fadiga), amarelo (ideal para dias nublados e direção noturna), e espelhado (máxima proteção e estilo moderno). Para pessoas com presbiopia, confeccionamos lentes de sol multifocais que permitem visão nítida para longe e perto com proteção solar completa. Lentes fotossensíveis também estão disponíveis, escurecendo automaticamente conforme a intensidade da luz solar. Todos os óculos de sol com grau recebem tratamento antirreflexo na face interna para eliminar reflexos indesejados e garantir conforto visual máximo. O prazo de confecção é de 7 a 10 dias úteis, e oferecemos garantia completa tanto para a armação quanto para as lentes graduadas."
    },
    {
      question: "Quais cuidados especiais devo ter com lentes de contato durante atividades esportivas?",
      answer: "As lentes de contato são excelentes para atividades esportivas, oferecendo campo visual amplo e liberdade de movimento que os óculos não proporcionam. Na Ótica Gouveia, orientamos nossos clientes sobre cuidados específicos para garantir segurança e conforto durante a prática esportiva. Para esportes aquáticos, recomendamos lentes de contato diárias descartáveis para evitar contaminação por microorganismos presentes na água. Nunca utilize lentes durante natação, mergulho ou esportes aquáticos sem óculos de proteção adequados, pois a água pode causar infecções graves. Em esportes de contato como futebol, basquete ou artes marciais, prefira lentes gelatinosas que são mais flexíveis e menos propensas a causar lesões em caso de impacto. Para atividades ao ar livre, combine lentes de contato com óculos de sol para proteção UV adicional. Durante exercícios intensos, a produção de lágrimas pode diminuir, causando ressecamento - mantenha sempre colírio lubrificante específico para uso com lentes de contato. Após atividades esportivas, lave bem as mãos antes de manusear as lentes, pois suor e sujeira podem contaminar o produto. Para esportes de aventura como ciclismo ou escalada, considere lentes de silicone hidrogel que permitem maior oxigenação da córnea. Mantenha sempre um kit de emergência com estojo, soro fisiológico e óculos de reserva. Se sentir qualquer desconforto durante a atividade, remova imediatamente as lentes e procure orientação profissional."
    }
  ];

  return (
    <section className="py-16 px-4 bg-gradient-to-br from-background to-secondary/10">
      <div className="container mx-auto max-w-4xl">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-4 bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
            Perguntas Frequentes
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Tire todas as suas dúvidas sobre nossos produtos e serviços especializados
          </p>
        </div>

        <Accordion type="single" collapsible className="w-full">
          {faqs.map((faq, index) => (
            <AccordionItem key={index} value={`item-${index}`} className="border-border/50">
              <AccordionTrigger className="text-left hover:text-primary transition-colors">
                <span className="font-medium">{faq.question}</span>
              </AccordionTrigger>
              <AccordionContent className="text-muted-foreground leading-relaxed">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
};

export default FAQ;